# Generated by Django 6.0.6 on 2026-08-12 09:46

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('office', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('gstin', models.CharField(blank=True, max_length=20, verbose_name='GSTIN')),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(blank=True, max_length=20, unique=True)),
                ('invoice_date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('po_no', models.CharField(blank=True, max_length=100, verbose_name='Your PO No.')),
                ('po_date', models.DateField(blank=True, null=True, verbose_name='PO Date')),
                ('dc_no', models.CharField(blank=True, max_length=100, verbose_name='DC No')),
                ('rr_lr_rpp_no', models.CharField(blank=True, max_length=100, verbose_name='RR/LR/RPP No')),
                ('rr_lr_rpp_date', models.DateField(blank=True, null=True, verbose_name='RR/LR/RPP Date')),
                ('from_place', models.CharField(default='Chennai', max_length=100)),
                ('to_place', models.CharField(blank=True, max_length=100)),
                ('tax_type', models.CharField(choices=[('auto', 'Auto (based on client state)'), ('igst', 'IGST 18%'), ('cgst_sgst', 'CGST 9% + SGST 9%')], default='auto', max_length=10)),
                ('igst_rate', models.DecimalField(decimal_places=2, default=Decimal('18.00'), max_digits=5)),
                ('cgst_rate', models.DecimalField(decimal_places=2, default=Decimal('9.00'), max_digits=5)),
                ('sgst_rate', models.DecimalField(decimal_places=2, default=Decimal('9.00'), max_digits=5)),
                ('p_and_f', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Add: P & F')),
                ('insurance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('less_advance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Less: Advance')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('taxable_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('igst_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('cgst_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('sgst_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('round_off', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('grand_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('amount_in_words', models.CharField(blank=True, max_length=300)),
                ('notes', models.TextField(blank=True, help_text='Leave blank to use the standard terms.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('authorized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorized_invoices', to='office.staff')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='billing.client')),
                ('prepared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepared_invoices', to='office.staff')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'ordering': ['-invoice_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300, verbose_name='Item / Description')),
                ('model_no', models.CharField(blank=True, max_length=100, verbose_name='Model')),
                ('hsn_code', models.CharField(blank=True, max_length=30, verbose_name='HSN Code')),
                ('serial_no', models.CharField(blank=True, max_length=200, verbose_name='Serial No(s)')),
                ('qty', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10)),
                ('unit', models.CharField(default='Nos', max_length=20)),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=12)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='billing.invoice')),
            ],
            options={
                'verbose_name': 'Line Item',
                'verbose_name_plural': 'Line Items',
                'ordering': ['id'],
            },
        ),
    ]
