# Generated by Django 6.0.6 on 2026-08-22 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_client_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='document_type',
            field=models.CharField(choices=[('invoice', 'Invoice'), ('proforma', 'Proforma Invoice')], default='invoice', max_length=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_no',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='Invoice No.'),
        ),
    ]
