# Generated by Django 6.0.6 on 2026-08-24 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_invoice_document_type_alter_invoice_invoice_no'),
        ('office', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_no',
            field=models.CharField(blank=True, max_length=20, verbose_name='Invoice No.'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(fields=('document_type', 'invoice_no'), name='unique_invoice_no_per_document_type'),
        ),
    ]
