# Generated by Django 6.0.6 on 2026-08-27 09:01

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_alter_invoice_invoice_no_and_more'),
        ('office', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('contact_person', models.CharField(blank=True, max_length=150)),
                ('gstin', models.CharField(blank=True, max_length=20, verbose_name='GSTIN')),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Supplier',
                'verbose_name_plural': 'Suppliers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_no', models.CharField(blank=True, max_length=30, verbose_name='PO Ref No.')),
                ('po_date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('ref_no', models.CharField(blank=True, max_length=100, verbose_name='Ref No.')),
                ('ref_date', models.DateField(blank=True, null=True, verbose_name='Ref Date')),
                ('contact_person', models.CharField(blank=True, max_length=150)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('currency', models.CharField(choices=[('INR', '₹ INR'), ('USD', '$ USD'), ('EUR', '€ EUR')], default='INR', max_length=3)),
                ('from_place', models.CharField(default='Chennai', max_length=100)),
                ('to_place', models.CharField(blank=True, max_length=100)),
                ('tax_type', models.CharField(choices=[('auto', 'Auto (based on supplier state)'), ('igst', 'IGST 18%'), ('cgst_sgst', 'CGST 9% + SGST 9%'), ('none', 'NA (No GST)')], default='auto', max_length=10)),
                ('igst_rate', models.DecimalField(decimal_places=2, default=Decimal('18.00'), max_digits=5)),
                ('cgst_rate', models.DecimalField(decimal_places=2, default=Decimal('9.00'), max_digits=5)),
                ('sgst_rate', models.DecimalField(decimal_places=2, default=Decimal('9.00'), max_digits=5)),
                ('delivery_date', models.DateField(blank=True, null=True, verbose_name='Delivery Date')),
                ('payment_terms', models.CharField(blank=True, default='100% advance', max_length=300)),
                ('delivery', models.CharField(blank=True, default='2-3 days', max_length=100)),
                ('freight', models.CharField(blank=True, default='Our Scope', max_length=150)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('taxable_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('igst_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('cgst_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('sgst_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('round_off', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('grand_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('notes', models.TextField(blank=True, help_text='Leave blank to use the standard notes.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prepared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepared_pos', to='office.staff')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='billing.supplier')),
            ],
            options={
                'verbose_name': 'Purchase Order',
                'verbose_name_plural': 'Purchase Orders',
                'ordering': ['-po_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300, verbose_name='Item')),
                ('qty', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10)),
                ('unit', models.CharField(default='Nos', max_length=20)),
                ('unit_price', models.DecimalField(decimal_places=4, default=Decimal('0.00'), max_digits=12)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=14)),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='billing.purchaseorder')),
            ],
            options={
                'verbose_name': 'Line Item',
                'verbose_name_plural': 'Line Items',
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='purchaseorder',
            constraint=models.UniqueConstraint(fields=('po_no',), name='unique_po_no'),
        ),
    ]
