# Generated by Django 6.0.6 on 2026-06-08 23:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('excerpt', models.CharField(max_length=300)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='blog/')),
                ('meta_title', models.CharField(blank=True, max_length=60)),
                ('meta_desc', models.CharField(blank=True, max_length=160)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('short_desc', models.CharField(blank=True, help_text='One line shown on product card', max_length=200)),
                ('description', models.TextField(help_text='Full product description — min 150 words for SEO')),
                ('specifications', models.JSONField(blank=True, default=dict, help_text='{"Flow Rate": "0–100 ml/min", "Voltage": "12V DC"}')),
                ('applications', models.TextField(blank=True, help_text='Comma-separated: Lab, Pharma, Food & Beverage')),
                ('price_label', models.CharField(blank=True, help_text='e.g. "Get Best Quote" or "₹4,500 onwards"', max_length=100)),
                ('stock_status', models.CharField(choices=[('available', 'Available'), ('on_request', 'On Request'), ('discontinued', 'Discontinued')], default='available', max_length=20)),
                ('is_featured', models.BooleanField(default=False, help_text='Show on homepage featured section')),
                ('is_active', models.BooleanField(default=True)),
                ('meta_title', models.CharField(blank=True, help_text='Max 60 chars — auto-generated if blank', max_length=60)),
                ('meta_desc', models.CharField(blank=True, help_text='Max 160 chars — shown in Google search results', max_length=160)),
                ('meta_keywords', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='ti-folder', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('meta_title', models.CharField(blank=True, max_length=60)),
                ('meta_desc', models.CharField(blank=True, max_length=160)),
            ],
            options={
                'verbose_name': 'Product Category',
                'verbose_name_plural': 'Product Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductDivision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='ti-package', help_text='Tabler icon class e.g. ti-ripple', max_length=50)),
                ('color', models.CharField(default='#185FA5', help_text='Hex colour for UI accents', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Product Division',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('company', models.CharField(blank=True, max_length=150)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(default='India', max_length=100)),
                ('product_name', models.CharField(blank=True, help_text='Filled if product not in DB', max_length=200)),
                ('message', models.TextField()),
                ('quantity', models.CharField(blank=True, max_length=50)),
                ('source', models.CharField(choices=[('visa_main', 'VISA Main Site'), ('pump_site', 'Peristaltic Pump Site'), ('hart_site', 'HART Communicator Site')], default='visa_main', max_length=20)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('converted', 'Converted'), ('closed', 'Closed')], default='new', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enquiries', to='shared.product')),
            ],
            options={
                'verbose_name': 'Enquiry / Lead',
                'verbose_name_plural': 'Enquiries / Leads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shared.productcategory'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='shared.productdivision'),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/%Y/%m/')),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('is_primary', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shared.product')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
