# Generated by Django 6.0.6 on 2026-06-17 06:59

import visa_group.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pdf_brochure',
            field=models.FileField(blank=True, help_text='Upload product brochure PDF — shown as download button on product page', null=True, storage=visa_group.storage.CloudinaryRawStorage(), upload_to='product_pdfs/'),
        ),
    ]
