# Generated by Django 6.0.6 on 2026-06-26 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0002_product_pdf_brochure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='message',
            field=models.TextField(blank=True, default=''),
        ),
    ]
