# Generated by Django 6.0.6 on 2026-07-10 09:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Staff',
                'verbose_name_plural': 'Staff',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VoucherDebitAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('voucher_type', models.CharField(choices=[('bank', 'Bank Voucher'), ('cash', 'Cash Voucher'), ('both', 'Both')], default='both', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Debit Account',
                'verbose_name_plural': 'Debit Accounts',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_type', models.CharField(choices=[('bank', 'Bank Voucher'), ('cash', 'Cash Voucher')], default='bank', max_length=10)),
                ('voucher_no', models.CharField(blank=True, max_length=20, unique=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('pay_to', models.CharField(max_length=200)),
                ('account_no', models.CharField(blank=True, max_length=100, verbose_name='A/c (Account No)')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_in_words', models.CharField(blank=True, max_length=300)),
                ('towards', models.TextField()),
                ('chq_no', models.CharField(blank=True, max_length=50, verbose_name='Cheque No')),
                ('chq_date', models.DateField(blank=True, null=True, verbose_name='Cheque Date')),
                ('drawn_on', models.CharField(blank=True, max_length=150, verbose_name='Drawn On (Bank)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_vouchers', to='office.staff')),
                ('checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_vouchers', to='office.staff')),
                ('prepared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepared_vouchers', to='office.staff')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_vouchers', to='office.staff')),
                ('debit_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vouchers', to='office.voucherdebitaccount')),
            ],
            options={
                'verbose_name': 'Voucher',
                'verbose_name_plural': 'Vouchers',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
